---
title: "Reproducible Research: Peer Assessment 1"
author: "Anastasia Illarionova"
output: 
     html_document:
          keep_md: true
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set( fig.path = "figure/fig-")

```
## Loading and preprocessing the data

```{r loaddata, echo=TRUE}
library(readr)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))

df = read.csv('activity.csv')
```

## What is mean total number of steps taken per day?

```{r histogram, echo=TRUE}
steps_per_day = aggregate(steps~date, data=df, sum)
hist(steps_per_day$steps, main="Total number of steps per day", 
     xlab="Steps")
mean_steps = mean(steps_per_day$steps, na.rm = TRUE)
median_steps = median(steps_per_day$steps, na.rm = TRUE)
print(paste0("The mean number of steps is ", mean_steps))
print(paste0("The median number of steps is ", median_steps))

```

## What is the average daily activity pattern?

```{r timeseries, echo=TRUE}

df_av = df %>% 
        group_by(interval) %>%
        summarize(mean_step = mean(steps, na.rm = TRUE), .groups = 'drop') 

ggplot(df_av, aes(interval, mean_step)) +
        geom_line()

max_interval = df_av$interval[which.max(df_av$mean_step)]
print(paste0("5-minute interval which contains the maximum number of steps is ", max_interval))

```

## Imputing missing values

```{r missingvalues, echo=TRUE}
na_summary = table(is.na(df$steps))
print(paste0("Number of missing values is ", as.numeric(na_summary[2])))
df_im = df
df_im$steps[which(is.na(df_im$steps))] = median_steps

steps_per_day_im = aggregate(steps~date, data=df_im, sum)

hist(steps_per_day_im$steps, main ="Total number of steps in imputed df", xlab="Steps")
mean_steps_im= mean(df_im$steps, na.rm = TRUE)
median_steps_im = median(df_im$steps, na.rm = TRUE)

print(paste0("Imputing of missing values affected median value and caused its decrease: (", median_steps, " in original dataset vs ", median_steps_im," in imputed dataset)"))
print(paste0("Imputing of missing values affected mean value and caused its decrease: (", mean_steps, " in original dataset vs ", mean_steps_im," in imputed dataset)"))

```

## Are there differences in activity patterns between weekdays and weekends?

```{r weekends, echo=TRUE}
df_im$date = strptime(df_im$date, format = "%Y-%m-%d")
df_im$weekday = weekdays(df_im$date)
df_im$weekend <- ifelse(weekdays(df_im$date) %in% c("Samstag", "Sonntag"), "weekend", "weekday")
df_im_av = df_im %>% 
        group_by(weekend, interval) %>%
        summarize(mean_step = mean(steps, na.rm = TRUE), .groups = 'drop')
ggplot(df_im_av, aes(interval, mean_step, col = weekend)) +
        geom_line()+ facet_grid(weekend ~ .)+ theme(legend.position = "none")

```
